import type {Metadata} from "next";
import { Space_Grotesk, Funnel_Sans} from "next/font/google";
import "./globals.css";
import MobileNav from "@/app/_components/MobileNav";

const spaceGrotesk = Space_Grotesk({
        subsets: ["latin"],
        display: "swap",
        weight: ["300", "400", "500", "600", "700"]
    }
);

const funnelSans = Funnel_Sans({
        subsets: ["latin"],
        display: "swap",
        weight: ["300", "400", "500", "600", "700", "800"]
    }
)

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${spaceGrotesk.className} ${funnelSans.className} h-dvh w-full relative antialiased dark-bg text-[#FFFDF6] `}
        >
        <nav className="h-18 w-full relative overflow-hidden">
            <MobileNav/>
        </nav>
        <main className="h-[calc(100%-4.5rem)] overflow-hidden scrollbar-hide"> {children}</main>
        </body>
        </html>
    );
}
