import type {Metadata} from "next";
import {Space_Grotesk, Funnel_Sans} from "next/font/google";
import "@/app/globals.css";
import MobileNav from "@/app/_components/MobileNav";
import {Suspense} from "react";
import Loading from "@/app/_components/Loading";
import { ToastContainer, Bounce } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const spaceGrotesk = Space_Grotesk({
        subsets: ["latin"],
        display: "swap",
        weight: ["300", "400", "500", "600", "700"]
    }
);

const funnelSans = Funnel_Sans({
        subsets: ["latin"],
        display: "swap",
        weight: ["300", "400", "500", "600", "700", "800"]
    }
)

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by uploadpg next app",
};

export default function AuthLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${spaceGrotesk.className} ${funnelSans.className} h-dvh w-full relative antialiased dark-bg text-[#FFFDF6] `}
        >
        <nav className="h-18 w-full relative overflow-hidden">
            <MobileNav/>
        </nav>
        <Suspense fallback={<Loading/>}>
            <main className="h-[calc(100%-4.5rem)] overflow-y-auto overflow-x-hidden scrollbar-hide"> {children}</main>
        </Suspense>
        <ToastContainer
            position="top-center"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
            transition={Bounce}
        />
        </body>
        </html>
    );
}
